name: Remastersys Live CD Build

on:
  push:
    branches:
      - main  # 触发分支
  workflow_dispatch:  # 支持手动触发

jobs:
  build-livecd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-config-systemd syslinux-common syslinux-efi syslinux-utils zstd coreutils

      - name: Clone Remastersys repository
        run: |
          git clone https://github.com/nerun/remastersys.git
          cd remastersys

      - name: Create Debian packages
        run: |
          cd remastersys
          ./package-creator
          sudo apt install ./remastersys*.deb

      - name: Create CDFS
        run: |
          sudo remastersys dist cdfs  # 创建 CD 文件系统

      - name: Create Live CD ISO
        run: |
          sudo remastersys dist iso custom.iso  # 生成自定义的 ISO 文件

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom.iso  # 自定义的 ISO 文件名
          path: /home/remastersys/remastersys/custom.iso  # 假设 ISO 文件生成路径
