name: Build and Upload Debian Live Image

on:
  push:
    branches:
      - debian

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest  # 使用最新的 Debian 镜像

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 更新包列表并安装必要的工具
          apt-get update
          apt-get install -y live-build

      - name: Create live-build directory
        run: |
          # 创建 live-build 工作目录
          mkdir -p /live-build

      - name: Run lb config to generate configuration files
        run: |
          # 运行 lb config 生成配置文件
          cd /live-build
          lb config

      - name: Build Debian Live Image
        run: |
          # 构建 Debian Live 镜像
          cd /live-build
          lb build

      - name: Copy output files to GitHub Actions workspace
        run: |
          # 将生成的文件复制到 GitHub Actions 工作区
          mkdir -p /github/workspace/output
          cp -r /live-build/binary/* /github/workspace/output/

      - name: Create and upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}_debian
          name: ${{ github.run_number }}_debian
          body: "谢谢使用"
          files: |
            /github/workspace/output/*.iso
          token: ${{ secrets.GITHUB_TOKEN }}
