name: Build and Upload Debian Live Image

on:
  push:
    branches:
      - debian

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: 清理磁盘空间
        #uses: jlumbroso/free-disk-space@main
        #with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          #tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          #android: true
      - name: Checkout repository
        uses: actions/checkout@v4

      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          docker build -t live-build-container .
          docker run --privileged --rm -v $(pwd)/output:/live-build/output live-build-container
          ls ./output

      
      - name: 创建并上传 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}_debian  # 使用推送的标签名
          name: ${{ github.run_number }}_debian
          body: "谢谢使用"  # Release 描述
          files: |
            ./output/*.iso
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
