name: 定时构建自定义chroot
on:
  schedule:
    - cron: '0 0 * * *'
env:
  PKG: "git nginx python3-pip"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [jammy, noble]
        architecture: [amd64]
    steps:
      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools xorriso grub-common grub-efi-amd64 mtools p7zip-full

      - name: 创建 LiveCD
        run: |
          set -e
          mkdir -p ~/livecd
          cd ~/livecd
          sudo debootstrap --arch=${{ matrix.architecture }} ${{ matrix.ubuntu_version }}} chroot http://archive.ubuntu.com/ubuntu/

          sudo mount --bind /dev chroot/dev
          sudo mount --bind /run chroot/run
          sudo mount --bind /proc chroot/proc

          echo "deb http://archive.ubuntu.com/ubuntu ${{ github.event.inputs.ubuntu_version }} universe" | sudo tee -a chroot/etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu ${{ github.event.inputs.ubuntu_version }}-updates universe" | sudo tee -a chroot/etc/apt/sources.list

          sudo chroot chroot /bin/bash -c "apt-get update && apt-get install -y linux-image-generic ${{ env.PKG }}"

          
          sudo pkill -9 -f "./chroot" || true
          sudo umount -l chroot/dev
          sudo umount -l chroot/run
          sudo umount -l chroot/proc

          

      
      - name: 设置版本号
        run: echo "VERSION=$(date +"%Y%m%d")" >> $GITHUB_ENV

      - name: 压缩
        run: |
          cd ~/livecd/chroot
          ls -a | xargs sudo tar -czvf ../ubuntu_chroot.tar.gz
          cd ..
          sudo rm -rf chroot
      - name: 分割文件
        run: |
          split -b 1G ~/livecd/ubuntu_chroot.tar.gz ./part_
      - name: 创建并上传 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # 使用推送的标签名
          name: ${{ env.VERSION }}  # Release 名称
          body: "请先合并下载的所有文件再使用"  # Release 描述
          files: |
            ./part_*
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
      
          
