name: 构建U盘引导

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [jammy, noble]
        architecture: [amd64]
    
    steps:
      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true

      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          
          sudo apt-get update
          sudo apt-get install -y debootstrap xorriso mtools e2fsprogs refind

      - name: 创建boot.img
        run: |
          sudo mkdir -p ~/ubuntu-usb
          cd ~/ubuntu-usb
          sudo dd if=/dev/zero of=boot.img bs=1M count=5120
          
          sudo mkfs.fat -F 32 boot.img
          

      - name: 安装rEFInd
        run: |
          cd ~/ubuntu-usb
          sudo refind-install --usedefault boot.img
          sleep 5
          sudo mkdir -p boot
          sudo mount boot.img boot
      - name: 创建efi.img并复制boot.img内容
        run: |
          cd ~/ubuntu-usb
          sudo dd if=boot.img of=efi.img bs=1M count=100
          

      - name: 复制宿主机内核文件到boot.img
        run: |
          cd ~/ubuntu-usb
          sudo cp /boot/vmlinuz-$(uname -r) boot/vmlinuz

      - name: 创建initrd.img
        run: |
          cd ~/ubuntu-usb
          sudo dd if=/dev/zero of=initrd.img bs=1M count=3072
          
          sudo mkfs.ext4 initrd.img
          sudo mkdir -p root
          sudo mount initrd.img root

      - name: 创建基础系统
        run: |
          cd ~/ubuntu-usb
          sudo debootstrap --arch=${{ matrix.architecture }} ${{ matrix.ubuntu_version }} root
          sudo cp efi.img root/efi.img
          sudo mount --bind /dev root/dev
          sudo mount --bind /run root/run
          sudo mount --bind /proc root/proc
          echo "deb https://archive.ubuntu.com/ubuntu/ ${{ matrix.ubuntu_version }} universe" | sudo tee -a root/etc/apt/sources.list
          echo "deb https://archive.ubuntu.com/ubuntu/ ${{ matrix.ubuntu_version }}-updates universe" | sudo tee -a root/etc/apt/sources.list
          sudo chroot root /bin/bash -c "apt-get update && apt-get install -y python3-pip"
          if [ "${{ matrix.ubuntu_version }}" = "noble" ]; then
              sudo chroot root /bin/bash -c "pip3 install --break-system-packages flask py7zr"
          else
              sudo chroot root /bin/bash -c "pip3 install flask py7zr"
          fi
          

      - name: 复制install目录到root目录
        run: |
          sudo cp -r install ~/ubuntu-usb/root/install
          cd ~/ubuntu-usb

      - name: 创建安装脚本
        run: |
          cd ~/ubuntu-usb
          # 创建安装脚本
          cat <<EOF | sudo tee root/init
          #!/bin/bash
          echo "Starting initrd as root filesystem..."
          mount -t proc none /proc
          mount -t sysfs none /sys
          /bin/busybox --install -s
          cd /install
          /usr/bin/python3 app.py
          EOF
          sudo chmod +x root/init
          
          sudo chroot root /bin/bash -c "echo -e '1234\n1234' | passwd root"

      - name: 复制initrd.img到boot.img
        run: |
          cd ~/ubuntu-usb
          sudo umount -l root
          sudo rm -rf root
          sudo cp initrd.img boot/initrd.img
          sudo rm -f initrd.img
          sudo umount -l boot
          sleep 5
          sudo rm -rf boot

      - name: 分割boot.img
        run: |
          split -b 1G ~/ubuntu-usb/boot.img ./boot_part_

      - name: 设置版本号
        run: echo "VERSION=$(date +"%Y%m%d")_boot_${{ matrix.ubuntu_version }}_${{ matrix.architecture }}" >> $GITHUB_ENV

      - name: 创建并上传 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: "root密码为1234，请先下载以boot开头的所有文件，然后运行copy /b boot_part_* boot.img（Windows系统命令）以合并文件"
          files: |
            ./boot_part_*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 清理工作目录
        run: |
           sudo rm -rf ~/ubuntu-usb
