name: Build and Upload Debian Live Image

on:
  workflow_dispatch:
    inputs:
      custom_packages:
        description: '请输入要安装的软件包（英文逗号分隔，不能有空格）'
        required: false
        default: ''
      debian_version:
        description: '请选择Debian版本'
        required: true
        default: 'bullseye'
        type: choice
        options:
          - bullseye
          - bookworm
          - sid
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

jobs:
  build_manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y live-build xorriso

      - name: Create live-build directory
        run: |
          mkdir -p /live-build

      - name: Run lb config to generate configuration files
        run: |
          cd /live-build
          lb config --distribution ${{ github.event.inputs.debian_version }}

      - name: Add custom packages to packages.list (if provided)
        if: github.event.inputs.custom_packages != ''
        run: |
          cd /live-build
          mkdir -p config/package-lists
          echo "${{ github.event.inputs.custom_packages }}" | tr ',' '\n' > config/package-lists/custom.list.chroot

      - name: Build Debian Live Image
        run: |
          cd /live-build
          lb build

      
          

      - name: Create and upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}_debian_${{ github.event.inputs.debian_version }}
          name: v${{ github.run_number }}_debian_${{ github.event.inputs.debian_version }}
          body: "谢谢使用"
          files: |
            /live-build/*.iso
          token: ${{ secrets.GITHUB_TOKEN }}

  build_scheduled:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y live-build xorriso

      - name: Create live-build directory
        run: |
          mkdir -p /live-build

      - name: Run lb config to generate configuration files
        run: |
          cd /live-build
          lb config

      - name: Install GNOME desktop environment
        run: |
          cd /live-build
          mkdir -p config/package-lists
          echo "gnome-desktop-environment" > config/package-lists/custom.list.chroot

      - name: Build Debian Live Image
        run: |
          cd /live-build
          lb build

      

      - name: Create and upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.scheduled_at }}_debian_latest
          name: ${{ github.event.scheduled_at }}_debian_latest
          body: "谢谢使用"
          files: |
            /live-build/*.iso
          token: ${{ secrets.GITHUB_TOKEN }}
