
name: 构建U盘ubuntu镜像
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: '选择 Ubuntu 版本（例如 jammy 或 noble）'
        required: true
        default: 'noble'
        type: choice
        options:
          - jammy
          - noble
      packages:
        description: '需要安装的软件包列表（软件包名称之间用空格分隔，不需要请留空）'
        required: false
        default: ''
        type: string
      mirror_url:
        description: '写入u盘后使用的镜像站地址'
        required: true
        default: 'https://archive.ubuntu.com/ubuntu/'
        type: choice
        options:
          - https://archive.ubuntu.com/ubuntu/
          - https://mirrors.aliyun.com/ubuntu/
          - https://mirrors.tuna.tsinghua.edu.cn/ubuntu/
      use_wifi:
        description: '是否使用WiFi连接（否则使用有线连接）'
        required: true
        default: 'false'
        type: boolean
      ssid:
        description: 'WiFi名称'
        required: false
        type: string
      password:
        description: 'WiFi密码'
        required: false
        type: string
      
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 隐藏机密
        uses: hugcabbage/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: ubuntu_version,packages,mirror_url
      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true

      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap xorriso grub-efi-amd64 mtools e2fsprogs
      - name: 创建并挂载ubuntu-usb.img
        run: |
          mkdir -p ~/ubuntu-usb
          cd ~/ubuntu-usb
          # 创建一个空的img文件，大小根据实际需求调整
          sudo dd if=/dev/zero of=ubuntu-usb.img bs=1M count=4096
          # 使用 parted 创建分区表
          sudo parted ubuntu-usb.img --script \
            mklabel gpt \
            mkpart ESP fat32 1MiB 101MiB \
            set 1 boot on \
            mkpart primary ext4 101MiB 100%
            # 挂载镜像文件并格式化分区
            sudo kpartx -av ubuntu-usb.img
            sleep 5  # 等待设备映射完成
            sudo mkfs.fat -F 32 /dev/mapper/loop0p1
            sudo mkfs.ext4 /dev/mapper/loop0p2
          sudo mkdir -p root
          sudo mount /dev/mapper/loop0p2 root
      
      - name: 创建基础系统
        run: |
          cd ~/ubuntu-usb
          sudo debootstrap --arch=amd64 ${{ github.event.inputs.ubuntu_version }} root https://archive.ubuntu.com/ubuntu/
          sudo mount --bind /dev root/dev
          sudo mount --bind /run root/run
          sudo mount --bind /proc root/proc
          

          echo "deb https://archive.ubuntu.com/ubuntu/ ${{ github.event.inputs.ubuntu_version }} universe" | sudo tee -a root/etc/apt/sources.list
          echo "deb https://archive.ubuntu.com/ubuntu/ ${{ github.event.inputs.ubuntu_version }}-updates universe" | sudo tee -a root/etc/apt/sources.list

          
          # 复制内核文件和初始化RAM磁盘文件
          sudo cp /boot/vmlinuz root/boot/
          sudo cp /boot/initrd.img root/boot/
          sudo cp /boot/vmlinuz-* root/boot/
          sudo cp /boot/initrd.img-* root/boot/
      - name: 设置efi
        run: |
          sudo mkdir -p ~/ubuntu-usb/root/refind
          sudo cp -r refind/refind-bin-0.14.2/. ~/ubuntu-usb/root/refind
          cd ~/ubuntu-usb
          sudo chroot root /bin/bash -c "/refind/refind-install --usedefault /dev/mapper/loop0p1"
      - name: 创建安装脚本
        run: |
          cd ~/ubuntu-usb
          # 创建 rc-local.service 文件
          cat <<EOF | sudo tee root/etc/systemd/system/rc-local.service
          [Unit]
          Description=/etc/rc.local Compatibility
          ConditionPathExists=/etc/rc.local

          [Service]
          Type=forking
          ExecStart=/etc/rc.local start
          TimeoutSec=0
          StandardOutput=tty
          RemainAfterExit=yes
          SysVStartPriority=99

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo chroot root /bin/bash -c "sudo systemctl enable rc-local"
          sudo chroot root /bin/bash -c "sudo systemctl start rc-local"
          # 在chroot环境中添加自启动脚本
          sudo tee root/etc/rc.local <<EOF
          #!/bin/bash
          if [ "${{ github.event.inputs.use_wifi }}" = "true" ]; then
              sudo nmcli dev wifi connect ${{ github.event.inputs.ssid }} password ${{ github.event.inputs.password }}
          fi
          # 修改镜像站为用户选择的
          sudo sed -i 's|${{ github.event.inputs.mirror_url }}|http://archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list
          sudo sed -i 's|${{ github.event.inputs.mirror_url }}|https://archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list
          if [ "${{ github.event.inputs.packages }}" = "" ]; then
              sudo rm /etc/rc.local
              reboot
          fi
          # 安装用户输入的软件包
          sudo apt-get update && apt-get install -y ${{ github.event.inputs.packages }}
          # 删除自启动脚本
          sudo rm /etc/rc.local
          reboot
          EOF
          sudo chmod +x root/etc/rc.local
          sudo chroot root /bin/bash -c "echo -e '1234\n1234' | passwd root"
          sudo umount -l root/dev
          sudo umount -l root/run
          sudo umount -l root/proc
          sudo rm -rf root/refind
          sudo umount -l root
          sudo kpartx -dv ubuntu-usb.img
          sleep 10
          sudo rmdir root

      - name: 设置版本号
        run: echo "VERSION=v${{ github.run_number }}_usb" >> $GITHUB_ENV

      - name: 压缩img镜像
        run: |
          gzip -8 -k ~/ubuntu-usb/ubuntu-usb.img
          sudo cp ~/ubuntu-usb/ubuntu-usb.img.gz ubuntu-usb.img.gz

      
      - name: 创建并上传 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # 使用推送的标签名
          name: ${{ env.VERSION }}  # Release 名称
          body: "root密码为1234"  # Release 描述
          files: |
            ./ubuntu-usb.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN

      - name: 清理工作目录
        run: |
          sudo rm -rf ~/ubuntu-usb

