name: Build and Upload Debian Live Image

on:
  workflow_dispatch:
    inputs:
      custom_packages:
        description: '请输入要安装的软件包（英文逗号分隔，不能有空格）'
        required: false
        default: ''
      debian_version:
        description: '请选择Debian版本'
        required: true
        default: 'bullseye'
        type: choice
        options:
          - bullseye
          - bookworm
          - sid
      architecture:
        description: '请选择架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - i386
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

jobs:
  build_manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y live-build xorriso

      - name: Create live-build directory
        run: |
          mkdir -p /live-build

      - name: Run lb config to generate configuration files
        run: |
          cd /live-build
          lb config --distribution ${{ github.event.inputs.debian_version }} --architecture ${{ github.event.inputs.architecture }} --debian-installer live

      - name: Add custom packages to packages.list (if provided)
        run: |
          cd /live-build
          mkdir -p config/package-lists
          echo "debian-installer-launcher,${{ github.event.inputs.custom_packages }}" | tr ',' '\n' > config/package-lists/custom.list.chroot

      - name: Build Debian Live Image
        run: |
          cd /live-build
          lb build

      - name: Upload ISO to 123 Cloud Disk and get share link
        id: upload_and_share
        run: |
          python upload.py ${{ secrets.ACCESS_KEY }} ${{ secrets.SECRET_KEY }} manual ${{ github.run_number }}
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Create GitHub Release with share link
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}_debian_${{ github.event.inputs.debian_version }}_${{ github.event.inputs.architecture }}
          release_name: v${{ github.run_number }}_debian_${{ github.event.inputs.debian_version }}_${{ github.event.inputs.architecture }}
          body: "ISO 文件已上传到 123 云盘，点击以下链接下载：\n${{ steps.upload_and_share.outputs.share_url }}"

  build_scheduled:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y live-build xorriso

      - name: Create live-build directory
        run: |
          mkdir -p /live-build

      - name: Run lb config to generate configuration files
        run: |
          cd /live-build
          lb config

      - name: Add custom packages to packages.list (if provided)
        run: |
          cd /live-build
          mkdir -p config/package-lists
          echo "debian-installer-launcher debootstrap" > config/package-lists/custom.list.chroot

      - name: Build Debian Live Image
        run: |
          cd /live-build
          lb build
          echo "VER=$(date +'%Y%m%d')_debian_latest">>$GITHUB_ENV

      - name: Upload ISO to 123 Cloud Disk and get share link
        id: upload_and_share
        run: |
          python upload.py ${{ secrets.ACCESS_KEY }} ${{ secrets.SECRET_KEY }} scheduled
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Create GitHub Release with share link
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VER }}
          release_name: ${{ env.VER }}
          body: "ISO 文件已上传到 123 云盘，点击以下链接下载：\n${{ steps.upload_and_share.outputs.share_url }}"
