name: Build LiveCD

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools xorriso coreutils

      - name: Create LiveCD
        run: |
          # 创建工作目录
          mkdir -p ~/livecd
          cd ~/livecd

          # 使用 debootstrap 创建基础系统
          sudo debootstrap --arch=amd64 jammy chroot http://archive.ubuntu.com/ubuntu/ 

          # 挂载必要的文件系统
          sudo mount --bind /dev chroot/dev
          sudo mount --bind /run chroot/run
          sudo mount --bind /proc chroot/proc

          # 进入 chroot 环境并启用 universe 软件源
          echo "deb http://archive.ubuntu.com/ubuntu  jammy universe" | sudo tee -a chroot/etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu  jammy-updates universe" | sudo tee -a chroot/etc/apt/sources.list

          # 安装必要的包
          sudo chroot chroot /bin/bash -c "apt update && apt install --reinstall start-stop-daemon && apt install -y linux-image-generic live-boot systemd-sysv"

          # 解除挂载
          sudo umount chroot/dev
          sudo umount chroot/run
          sudo umount chroot/proc

          # 创建 squashfs 文件系统
          sudo mksquashfs chroot filesystem.squashfs -comp xz

          # 创建 ISO 文件
          sudo xorriso -as mkisofs -r -J -joliet-long -l -cache-inodes \
            -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -partition_offset 16 \
            -A "Ubuntu LiveCD" -b isolinux/isolinux.bin -c isolinux/boot.cat \
            -no-emul-boot -boot-load-size 4 -boot-info-table \
            -o ubuntu-livecd.iso binary

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu LiveCD ISO
          path: ~/livecd/ubuntu-livecd.iso
