name: Build Ubuntu LiveCD Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手动触发

jobs:
  build-livecd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update package list
        run: sudo apt-get update

      - name: Install live-build and dependencies
        run: |
          sudo apt-get install -y live-build xorriso coreutils

      - name: Create working directory
        run: sudo mkdir -p /live

      - name: Configure live-build
        run: |
          cd /live
          sudo lb config \
            --architectures amd64 \
            --linux-flavours generic \
            --binary-images iso-hybrid \
            --iso-application "Ubuntu Live" \
            --iso-preparer "Live Build" \
            --iso-publisher "Your Name" \
            --iso-volume "Ubuntu Live Volume" \
            --debian-installer live \
            --distribution jammy \
            --debootstrap-options "--variant=minbase"

      - name: Build LiveCD Image
        run: |
          cd /live
          sudo lb build

      - name: Upload LiveCD Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-live.iso
          path: /live/binary.hybrid.iso
