name: Build and Upload Debian Live Image

on:
  push:
    branches:
      - debian

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: insightsengineering/disk-space-reclaimer@v1
        with:
          tools-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          docker-images: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          docker build -t live-build-container .
          docker run --rm -v $(pwd)/output:/live-build/output live-build-container

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}_debian
          release_name: Release ${{ github.run_number }}_debian
          draft: false
          prerelease: false

      - name: Upload Debian Live Image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/image.iso  # 替换为实际生成的镜像文件路径
          asset_name: debian-live-image-${{ github.run_number }}_debian.iso
          asset_content_type: application/octet-stream
