name: tb
on:
  push:
      
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


      - name: 创建并挂载ubuntu-usb.img
        run: |
          mkdir -p ~/ubuntu-usb
          cd ~/ubuntu-usb
          # 创建一个空的img文件，大小根据实际需求调整
          sudo dd if=/dev/zero of=ubuntu-usb.img bs=1M count=4096
          # 使用 parted 创建分区表
          sudo parted ubuntu-usb.img --script \
            mklabel gpt \
            mkpart ESP fat32 1MiB 101MiB \
            set 1 boot on \
            mkpart primary ext4 101MiB 99%
            # 挂载镜像文件并格式化分区
            sudo kpartx -av ubuntu-usb.img
            sleep 5  # 等待设备映射完成
            sudo mkfs.fat -F 32 /dev/mapper/loop0p1
            sudo mkfs.ext4 /dev/mapper/loop0p2
            blkid /dev/mapper/loop0p2 -o value -s UUID
