name: Build LiveCD

on:
  push:

jobs:
  build-livecd:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build

      - name: Create build directory
        run: |
          sudo mkdir /live
          cd /live
          sudo lb config --architectures amd64 --binary-images iso-hybrid --distribution jammy --archive-areas "main restricted universe multiverse"
          mkdir -p config/hooks
          cat << 'EOF' > config/hooks/pre-start-stop-daemon.hook.chroot
          #!/bin/sh
          if [ -f /usr/sbin/start-stop-daemon ]; then
            mv /usr/sbin/start-stop-daemon /usr/sbin/start-stop-daemon.bak
          fi
          EOF
          sudo chmod +x config/hooks/pre-start-stop-daemon.hook.chroot
      
      - name: Build LiveCD
        run: |
          cd /live
          sudo lb build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: LiveCD Build ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload LiveCD ISO to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /live/live-image-*.iso
          asset_name: livecd-${{ github.run_number }}.iso
          asset_content_type: application/octet-stream
