name: Create Live CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso squashfs-tools dmraid lvm2 samba-common

      - name: Download Distroshare Ubuntu Imager
        run: |
          wget https://codeload.github.com/Distroshare/distroshare-ubuntu-imager/zip/master
          unzip master -d /tmp
          
      - name: Modify configuration file
        run: |
          sudo sed -i 's#WORK="/tmp/folder"#WORK="/tmp/livecd"#' /tmp/distroshare-ubuntu-imager-master/distroshare-ubuntu-imager.config
          sudo sed -i 's#ISO_NAME="live-cd.iso"#ISO_NAME="ubuntu-custom.iso"#' /tmp/distroshare-ubuntu-imager-master/distroshare-ubuntu-imager.config
      - name: Create Live CD
        run: |
          cd /tmp/distroshare-ubuntu-imager-master
          sudo ./distroshare-ubuntu-imager.sh
      - name: 设置版本号
        run: echo "VERSION=v${{ github.run_number }}_new" >> $GITHUB_ENV

      - name: 压缩
        run: |
          gzip -8 -k /tmp/livecd/ubuntu-custom.iso
      - name: 分割文件
        run: |
          split -b 1G /tmp/livecd/ubuntu-custom.iso.gz ./part_  # 按 1GB 分割文件
      - name: 创建并上传 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # 使用推送的标签名
          name: ${{ env.VERSION }}  # Release 名称
          body: "请先合并下载的所有文件再使用，root密码为1234"  # Release 描述
          files: |
            ./part_*
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GITHUB_TOKEN
      
