name: Format IMG to NTFS
on: [push]
jobs:
  format-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install ntfs-3g
        run: |
          sudo apt-get update
          sudo apt-get install -y ntfs-3g
      
