name: Find ISOLINUX Paths
on: [push, pull_request]
jobs:
  find-paths:
    runs-on: ubuntu-24.04
    steps:
      - name: Install syslinux
        run: |
          sudo apt-get update
          sudo apt-get install -y syslinux-common

      - name: Find isolinux.bin and ldlinux.c32 paths
        id: find-paths
        run: |
          ISOLINUX_PATH=$(find /usr -name "isolinux.bin" | head -n 1)
          LDLINUX_PATH=$(find /usr -name "ldlinux.c32" | head -n 1)
          ISOHDPFX_PATH=$(find /usr -name "isohdpfx.bin" | head -n 1)

          if [ -z "$ISOLINUX_PATH" ] || [ -z "$LDLINUX_PATH" ] || [ -z "$ISOHDPFX_PATH" ]; then
            echo "Error: Required files (isolinux.bin, ldlinux.c32, or isohdpfx.bin) not found!"
            exit 1
          fi

          echo "ISOLINUX_PATH=$ISOLINUX_PATH" >> $GITHUB_ENV
          echo "LDLINUX_PATH=$LDLINUX_PATH" >> $GITHUB_ENV
          echo "ISOHDPFX_PATH=$ISOHDPFX_PATH" >> $GITHUB_ENV

      - name: Print paths
        run: |
          echo "ISOLINUX_PATH: $ISOLINUX_PATH"
          echo "LDLINUX_PATH: $LDLINUX_PATH"
          echo "ISOHDPFX_PATH: $ISOHDPFX_PATH"
