name: Build Ubuntu Image

on:
  workflow_dispatch:
    inputs:
      distribution:
        description: 'Ubuntu distribution (jammy or noble)'
        required: true
        default: 'jammy'
      architecture:
        description: 'Architecture (amd64 or i386)'
        required: true
        default: 'amd64'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y live-build

    - name: Configure live-build
      run: |
        lb config --architecture ${{ github.event.inputs.architecture }} --distribution ${{ github.event.inputs.distribution }}

    - name: Create custom hook script
      run: |
        mkdir -p config/hooks/normal
        cat > config/hooks/normal/9000-move-start-stop-daemon.chroot <<EOF
        #!/bin/sh
        if [ -f /usr/sbin/start-stop-daemon ]; then
          mv /usr/sbin/start-stop-daemon /usr/sbin/start-stop-daemon.bak
        fi
        EOF
        chmod +x config/hooks/normal/9000-move-start-stop-daemon.chroot

    - name: Build the image
      run: |
        sudo lb build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-image
        path: binary.hybrid.iso
